// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbI_v39IMHr_zlg2Q5SeOzL24eORNzfdg',
    appId: '1:1075021078938:web:f8f1ec40287bbdd4e39a23',
    messagingSenderId: '1075021078938',
    projectId: 'taskmanagerapp-bccd5',
    authDomain: 'taskmanagerapp-bccd5.firebaseapp.com',
    storageBucket: 'taskmanagerapp-bccd5.firebasestorage.app',
    measurementId: 'G-LNQH4PX81E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHv6s-qWFGc6xwb9UqCOL8rd5_QpNCnXY',
    appId: '1:1075021078938:android:ebbac81d6735a8a8e39a23',
    messagingSenderId: '1075021078938',
    projectId: 'taskmanagerapp-bccd5',
    storageBucket: 'taskmanagerapp-bccd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmbQ4kGqhr2wN3BEgn415wwNXXljspHw',
    appId: '1:1075021078938:ios:c4fb3e076b3a25c4e39a23',
    messagingSenderId: '1075021078938',
    projectId: 'taskmanagerapp-bccd5',
    storageBucket: 'taskmanagerapp-bccd5.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUmbQ4kGqhr2wN3BEgn415wwNXXljspHw',
    appId: '1:1075021078938:ios:c4fb3e076b3a25c4e39a23',
    messagingSenderId: '1075021078938',
    projectId: 'taskmanagerapp-bccd5',
    storageBucket: 'taskmanagerapp-bccd5.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbI_v39IMHr_zlg2Q5SeOzL24eORNzfdg',
    appId: '1:1075021078938:web:e07e5bfef0974b3ee39a23',
    messagingSenderId: '1075021078938',
    projectId: 'taskmanagerapp-bccd5',
    authDomain: 'taskmanagerapp-bccd5.firebaseapp.com',
    storageBucket: 'taskmanagerapp-bccd5.firebasestorage.app',
    measurementId: 'G-BLMCLCBWDT',
  );
}
